config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  get 'books/index'
  get 'books/show'
  get 'books/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def edit
    end
    
    def index
      @books = Book.all
      @book = Book.new
    end
    
    def show
    end
    
    def create
       @book = Book.new(book_params)
       
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>

<p>Find me in app/views/boooks/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(user) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>New Book</h1>
 <%= form_with model: @book do |f| %>
 <div class="field">
  <lavel>Title</lavel><br>
  <%= f.text_field :title %><br>
 </div>
 <div class="field">
  <lavel>Body</lavel><br>
  <%= f.text_area :body %><br>
 </div>
  <%= f.submit 'Create Book' %>
 <% end %>

app/views/books/new.html.erb
<h1></h1>
<%= form_with model: List.new do |f| %>
  <%= f.text_field :title %>
<% end %>

app/views/books/show.html.erb
<%= link_to 'edit' 

app/views/homes/top.html.erb
<body>
 <h1>ようこそ <strong>Bookers</strong> へ!</h1>

 <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
 <p>印象を共有し交換することができます</p>

 <p>
  <a href= "https://7bf7cb3b80c744e9ae85348a75f59a46.vfs.cloud9.ap-northeast-1.amazonaws.com/books/index/" >start</a>
 </p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>